### ISSUE TITLE
How to use Harmon in SSL proxy server? 

### ISSUE THREAD

**Issue by liuxujin** [No9/harmon#11]
The code below is my sample code, where/how can I add the harmon code to modify the response? like this "require('harmon')([], actions),", where to add?

```
var proxySSL = httpProxy.createProxyServer({
  xfwd: true,
  ssl: httpsOpts,
  target: 'https://c45.target.com/profiles',
  secure: false
}
);
https.createServer(httpsOpts,
    function (req,res) {
        proxySSL.web(req, res);
    }
).listen(443);
```

**Comment by No9** [comment]
@liuxujim Gzip support and a sample has been added to the repo
https://github.com/No9/harmon/blob/master/examples/gzipped.js
