### ISSUE TITLE
rotate.js creates malformed HTML

### ISSUE THREAD

**Issue by GuyPaddock** [No9/harmon#16]
The example replaces the `<head>` tag with a style tag. I am guessing that the `outer` parameter should be `false`, or the tag should be included in the content that's added.

**Comment by No9** [comment]
sorry forgot about this.
Yes your right so I fixed it.

**Comment by tarkeshwars** [comment]
Hey @No9! I was trying the rotate example. It still replaces the entire head tag. Is it just me or the example still isn't fixed?

**Comment by No9** [comment]
Hi @tarkeshwars 
Yes it replaces all the content **inside** the head but not the head tag itself. 
That was the issue here. 
If you want an example of how you can manipulate the contents of a tag see 
https://github.com/No9/harmon/blob/master/examples/doge.js 

Thanks

**Comment by tarkeshwars** [comment]
My bad! But the rotate example has confusing comments. I think they should
be fixed. I got around to looking at the doge file and that was exactly
what I needed. So thanks :)
