### ISSUE TITLE
Select a tag, keep only inner content

### ISSUE THREAD

**Issue by cbioley** [No9/harmon#20]
Hello friends,

I’m rather new to the shiny stream adventure and I’m having a hard time to wrap my head around the following:

I would like to select a tag and only keep its inner content, like:

```
<div class="outer"><div class="inner"></div></div>
```
becomes
```
<div class="inner"></div>
```

Any help would be greatly appreciated :)

**Comment by No9** [comment]
Hey @cbioley  

I have updated the doge.js example to show how you might use a read/write stream to get all the info in a tag and then write something different. 

https://github.com/No9/harmon/blob/master/examples/doge.js#L13 

If you are finding streams a little tricky in general then I would recommend trying the nodeschool on it.

**Comment by cbioley** [comment]
Hmm, is there a prettier way of doing it?

```
var read = node.createReadStream();
var write = node.createWriteStream({outer: true});

read.pipe(write)
```

**Comment by cbioley** [comment]
Wow, almost concurrently ^^

Thanks, I'll look at it tomorrow (2:33 AM here ;))

**Comment by No9** [comment]
K but you are not doing anything with the content there
You could use through along with that approach but I didn't want to polute the example with additional modules.

**Comment by No9** [comment]
Lol that was mad :) 1:34 here 
Yup bed time

**Comment by cbioley** [comment]
Could not resist to look at what you just did. Thank you!

We have come full circle, because I just read about what you did + the fact it was not considered the best pattern ever (but as you said, it's on purpose as you didn't want to introduce a new module, I totally get that).

Yes, the objective was exactly that: removing the outer tag and keeping all the inner content as is.

I think streams are slooooowly starting to grow on me :)

**Comment by No9** [comment]
k can we close this then?

**Comment by cbioley** [comment]
Oh yeah, sure. Thanks again.
