### ISSUE TITLE
Replace just a word

### ISSUE THREAD

**Issue by jpacora** [No9/harmon#27]
Hello, i wanna replace a word from all the body, how i can do that?

**Comment by No9** [comment]
Hi @jpacora 
Can provide a gist with how far you have got with the problem?
The question is a litt

**Comment by jpacora** [comment]
For example y have the following: 
<div>Hello Pepe</div>
And i wanna show this:
<div>Hello Juan</div>

Replace "Pepe" with "Juan"

**Comment by No9** [comment]
Hi @jpacora
This library works uses html for navigation
Can you provide a sample Web page you are trying to parse and the Harmon selectors you have used so far
Thanks

**Comment by No9** [comment]
Hi @jpacora 
I am going to close this off. 
If you have an example then please feel free to reopen
